cafe-sur-cour/AREA

README.md
Updated project overview to clarify the purpose of the AREA platform.
=> README: Started the project overview

.gitignore, scripts/modules_update.py
This pull request introduces a new script, `scripts/modules_update.py`, that automates the tracking and updating of progress for GitHub issues related to project modules. The script fetches all issues from the repository, identifies module-related issues, parses their sub-issues, calculates progress (including completed, in-progress, and blocked sub-issues), and updates the corresponding GitHub issue with the latest progress tracking information.
Key features and logic in the new script:
**Automated GitHub Issue Progress Tracking**
* Adds a script (`scripts/modules_update.py`) that fetches all issues from the repository using the GitHub API and filters for issues with `[MODULE]` in the title.
* Parses sub-issue references from the body of module issues and determines their completion …
=> SCRIPTS - Automated update modules

mobile/README.md
This pull request updates the `mobile/README.md` file to provide comprehensive instructions for setting up, running, and building the Flutter mobile app. The new documentation makes it easier for developers to get started and clarifies how to use CLI commands and project scripts for common workflows.
Documentation improvements:
* Added detailed installation instructions for Flutter, including a link to official documentation.
* Explained how to add and select devices for running the app, including using physical devices and emulators.
* Provided step-by-step instructions for starting the app using both CLI commands and project scripts, covering both debug and release modes.
* Included instructions for building the APK via CLI and scripts, with guidance on where to find the output file.
=> Update README installation instructions

backend/package.json, backend/src/services/services/timer/TimerScheduler.ts, backend/src/services/services/timer/actions.ts, backend/src/services/services/timer/index.ts, backend/src/services/services/timer/reactions.ts, backend/src/services/services/timer/schemas.ts, documentation/HOWTOCONTRIBUTE.md, documentation/services/SERVICES_ARCHITECTURE.md
This pull request introduces a new internal timer service to the backend, enabling scheduled actions to be triggered at specific times and intervals. The main changes include the implementation of the timer scheduler logic, the definition of timer actions and their configuration schemas, and updates to dependencies to support cron-based scheduling.
Timer service implementation:
* Added the `TimerScheduler` class in `TimerScheduler.ts`, which uses `node-cron` to periodically check and trigger timer-based actions, such as "every hour at intervals" and "every day at X hour". It interacts with the database to find active timer mappings and creates corresponding events.
* Created the `timer` service in `index.ts`, defining two actions (`every_day_at_x_hour` and `every_hour_at_intervals`) with …
=> backend - timer service actions

.github/workflows/cicd.yml, backend/index.ts, backend/package.json, deployment/docker-compose.yml
This pull request primarily improves cross-origin resource sharing (CORS) support for the backend and updates environment variable usage for Docker setup. The most important changes are grouped below by theme.
**CORS and Backend Configuration:**
* Added the `cors` middleware to `backend/index.ts`, configured to use the `FRONTEND_URL` environment variable and allow credentials for requests from the frontend. Also included manual CORS headers for additional compatibility. [[1]](diffhunk://#diff-bdce6c197e915a5e5fd34714b3512bf28eb09351d85d30346eb73e3823739de5R9-R11) [[2]](diffhunk://#diff-bdce6c197e915a5e5fd34714b3512bf28eb09351d85d30346eb73e3823739de5R22-R37)
* Added `cors` as a dependency in `backend/package.json` to support CORS middleware.
**Docker and Environment Variable Updates:**
* …
=> pull request (Backend): Implement cors between backend and frontend

backend/index.ts, backend/src/routes/about/about.ts
This pull request introduces a new `/about.json` API endpoint that provides information about the server, its current time, and the available services, including their actions and reactions. The endpoint also returns the client's host IP. This addition is accompanied by OpenAPI (Swagger) documentation for the new route.
New `/about.json` endpoint:
* Added a new route handler in `backend/src/routes/about/about.ts` that responds to GET requests on `/about.json` with server info, client IP, and a list of services, actions, and reactions. Includes Swagger documentation for API discoverability.
* Registered the new `aboutRoutes` in the main application by importing it in `backend/index.ts` [[1]](diffhunk://#diff-bdce6c197e915a5e5fd34714b3512bf28eb09351d85d30346eb73e3823739de5R16) and mounting …
=> feat (backend): /about.json implementation

backend/src/middleware/mail.ts, backend/src/routes/auth/auth.service.ts, backend/src/routes/auth/auth.ts, backend/src/utils/express.d.ts
This pull request introduces a robust password reset workflow to the authentication system, including new endpoints for requesting and completing password resets, token-based security, and improved error handling. It also adds middleware for token extraction and refines token payloads for registration and verification. The changes enhance both security and user experience.
**Password Reset Workflow**
* Added `/forgot-password` endpoint: Allows users to request a password reset. Generates a secure token and sends a reset email if the user exists, but always returns a generic success message to prevent email enumeration. Includes detailed Swagger documentation. (`backend/src/routes/auth/auth.ts`, `backend/src/routes/auth/auth.service.ts`) …
=> pull request (backend): Implement forgotten password and reset password

backend/index.ts, backend/src/config/db.ts, backend/src/config/entity/UserServiceConfigs.ts, backend/src/models/UserServiceConfig.ts, backend/src/routes/github/github.ts, backend/src/routes/services/configs.ts, backend/src/routes/user/user.ts, backend/src/services/ExecutionService.ts, backend/src/services/ServiceRegistry.ts, backend/src/services/UserServiceConfigService.ts, backend/src/services/services/github/actions.ts, backend/src/services/services/github/index.ts, backend/src/services/services/github/schemas.ts, backend/src/services/services/github/webhookManager.ts, backend/src/types/webhook.ts, backend/src/webhooks/WebhookLoader.ts, backend/src/webhooks/github/index.ts, backend/src/webhooks/index.ts, database/table/external_webhooks.sql, documentation/HOWTOCONTRIBUTE.md, documentation/services/SERVICES_ARCHITECTURE.md
This pull request introduces user-specific service configuration management and GitHub webhook management to the backend API. It adds new database entities, API endpoints, and service logic to allow users to securely store, retrieve, update, and delete their service credentials and settings, as well as manage GitHub OAuth status and webhooks. Additionally, the execution service now loads and uses actual user service configurations during event processing, and logging has been improved for better traceability.
**Key changes:**
**Service Configuration Management:**
- Added a new entity (`UserServiceConfigs`) and corresponding TypeScript model to store user-specific service credentials and settings in the database. [[1]](diffhunk://#diff-f6d2e4d5ebb7575e7b388741ae8fd8367ad7935f0e7c7d033fa2a53 …
=> backend - implement actions

.github/workflows/cicd.yml, deployment/Dockerfile.mobile, mobile/lib/screens/add_automation_screen.dart, mobile/lib/screens/forgot_password_screen.dart, mobile/lib/screens/login_screen.dart, mobile/lib/screens/profile_screen.dart, mobile/lib/screens/register_screen.dart, mobile/pubspec.yaml, mobile/test/widget_test.dart
This pull request adds full support for mobile (Flutter) builds and testing to the CI/CD pipeline, ensuring that changes to the mobile codebase are properly linted, tested, and deployed. It introduces new workflow steps, updates the mobile Dockerfile for real APK builds, and adjusts test scaffolding for compatibility.
**CI/CD Pipeline Enhancements**
* Added detection of mobile changes in `.github/workflows/cicd.yml` so that mobile-related jobs are triggered only when relevant files are modified. [[1]](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0R16) [[2]](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0R38) [[3]](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0R56) …
=> Added CI and CD for Mobile app

backend/index.ts, backend/src/config/adminJs.ts, backend/src/config/db.ts, backend/src/config/entity/UserServiceSubscriptions.ts, backend/src/config/passport.ts, backend/src/routes/auth/auth.ts, backend/src/routes/github/github.ts, backend/src/routes/google/google.ts, backend/src/services/ServiceSubscriptionManager.ts, backend/src/webhooks/github/index.ts, database/table/user_service_subscriptions.sql, web/app/services/page.tsx
This pull request introduces a new user service subscription system, enabling users to subscribe and unsubscribe to external services (starting with GitHub and Google). It adds a new database entity for tracking subscriptions, integrates subscription logic into the authentication flow, and provides new API endpoints for managing and checking subscription status. These changes improve service connection management and set the foundation for more granular event/webhook handling.
**Service Subscription System**
* Added the `UserServiceSubscriptions` entity to the database, enabling tracking of user subscriptions to external services.
* Registered `UserServiceSubscriptions` in both the database configuration (`db.ts`) and the admin panel configuration (`adminJs.ts`) so it is available for …
=> Fix service subscription

backend/src/routes/docs/swagger.ts, web/lib/load-env.ts
This pull request introduces two main changes to improve API documentation coverage and environment variable usage. The first change expands the Swagger documentation to include webhook routes, ensuring all API endpoints are properly documented. The second change updates the environment variable used for the backend URL to standardize configuration across environments.
API Documentation Improvements:
* Expanded the Swagger documentation sources to include files in `src/webhooks`, ensuring webhook endpoints are documented alongside standard API routes.
Environment Variable Standardization:
* Updated environment variable usage for the backend URL in `getEnv` to use `BACKEND_URL` instead of `NEXT_PUBLIC_API_URL`, promoting consistency in configuration.
=> fix (backend): url problems

backend/eslint.config.js, backend/package.json, backend/src/config/adminJs.ts, backend/src/config/dashboard.tsx, backend/src/config/dashboardService.ts
This pull request introduces a new dashboard statistics service and custom theming for the AdminJS admin panel, along with related configuration and dependency updates. The main improvements include a backend service for gathering dashboard data, a new API endpoint to expose these statistics, and the integration of a custom AdminJS theme.
**Dashboard statistics and API:**
* Added a new `DashboardService` class in `dashboardService.ts` to aggregate and provide statistics about users, services, webhooks, and recent activity for the admin dashboard. This includes error handling and fallback/mock data for missing tables.
* Registered an API endpoint `/api/dashboard-stats` in the admin router to serve the dashboard data using the new service.
**AdminJS customization and configuration:**
* …
=> 77 task backend admin manage users crud

backend/src/config/db.ts, backend/src/config/entity/Logger.ts, backend/src/routes/auth/auth.ts, backend/src/routes/logs/logs.service.ts, database/table/logs.sql
This pull request introduces a logging system for authentication events in the backend, enabling tracking of login and logout attempts, errors, and other relevant actions. The changes include the creation of a new `Logger` entity, a supporting database table, and integration of logging into the authentication routes.
**Logging system implementation:**
* Added a new `Logger` entity (`Logger.ts`) to represent log entries, with fields for log type, kind, timestamp, and message.
* Created a corresponding SQL table (`logs.sql`) and ENUM types for log type and kind to store log entries in the database.
**Integration with authentication routes:**
* Implemented the `createLog` service to create log entries based on authentication events, mapping HTTP status codes to log types.
* Updated the login …
=> pull request (backend): implement logs for user login and logout

web/components/UserActions.tsx
This pull request improves the user experience in the `UserActions` component by adding a loading state indicator. When authentication status is being determined, a spinner is displayed instead of the usual user actions.
User interface improvements:
* Added a loading spinner (`TbLoader3` from `react-icons/tb`) to the `UserActions` component, which is shown when the authentication context is loading. (`web/components/UserActions.tsx`)
* Updated the `useAuth` hook usage to include the `isLoading` property and conditionally render the spinner when loading. (`web/components/UserActions.tsx`)
=> Adding a loader in the header

web/contexts/AuthContext.tsx
This pull request introduces a small improvement to the logout functionality in the authentication context. The change ensures that any errors during the logout API request are caught and logged, making the logout process more robust and easier to debug.
=> Call Api on logout

backend/src/config/entity/WebhookEvents.ts, backend/src/routes/services/mappings.service.ts, backend/src/services/ExecutionService.ts, backend/src/services/ServiceSubscriptionManager.ts, backend/src/services/services/github/index.ts, backend/src/services/services/timer/TimerScheduler.ts, backend/src/services/services/timer/actions.ts, backend/src/types/service.ts
This pull request introduces several improvements and refactors to the backend services, focusing on timer and webhook mapping functionality, enhanced credential handling, and improved logging for debugging. The most significant changes are grouped below by theme.
* Standardized timer action IDs to use the prefix `timer.` (e.g., `timer.every_day_at_x_hour`, `timer.every_hour_at_intervals`) for consistency across the codebase. [[1]](diffhunk://#diff-109ab05906f05120f45915d88e2ccddeff43c22027da56f73b9bd7bb7ac090cbL6-R6) [[2]](diffhunk://#diff-109ab05906f05120f45915d88e2ccddeff43c22027da56f73b9bd7bb7ac090cbL34-R34)
* Updated timer mapping logic to use integer comparison for the minute field, improving reliability when triggering events at specific times. Also added a log statement when a …
=> fix (backend): a/r mapping executions

README.md, backend/src/config/entity/Logger.ts, backend/src/routes/auth/auth.ts, backend/src/routes/logs/logs.service.ts, database/table/logs.sql
This pull request enhances logging for authentication and password reset operations, adds a new log kind for user registration, and updates related database schema and code references. The changes improve auditability and error tracking for user-related actions.
**Logging and Audit Improvements:**
* Added detailed logging for registration, verification, and password reset events, including success and failure cases, by invoking `createLog` with appropriate status codes, kinds, and messages throughout `backend/src/routes/auth/auth.ts`. [[1]](diffhunk://#diff-278b414c47d2934820f3d227a5faa32d485d5e46baa854fe8317b38ee9f5609fR265-R273) [[2]](diffhunk://#diff-278b414c47d2934820f3d227a5faa32d485d5e46baa854fe8317b38ee9f5609fR335-R339) [[3]](diffhunk://#diff-278b414c47d2934820f3d227a5faa32d485d5e46 …
=> pull request (backend): implement register logs

backend/src/config/entity/Logger.ts, backend/src/routes/auth/auth.ts, backend/src/routes/logs/logs.service.ts, database/table/logs.sql
This pull request enhances the logging functionality for authentication events, specifically adding more detailed logging for GitHub and Google OAuth flows. The changes include expanding the types of log entries to cover these providers and ensuring that failed authentication attempts and missing tokens are logged for better traceability.
**Logging improvements for OAuth providers:**
* Expanded the `kind` enum in the `Logger` entity and related code to include `github` and `google`, allowing logs to distinguish between different authentication providers. [[1]](diffhunk://#diff-f4278a5292e56d9d5d2182f93e75a88aeb7cb92aea64eb70ead89baefd765b04L19-R21) [[2]](diffhunk://#diff-7e1f2189399103aacbc93dfed1b0908b3c540eab4fc107227a9e11f74d2aec88L6-R6) …
=> pull request (backend): implement Oauth logs

backend/src/routes/auth/auth.ts
This pull request makes a small update to the authentication redirect behavior. After successful authentication, the redirect URL now includes the user's token as a query parameter, which can be used by the frontend for further processing.
=> refactor (backend): update redirection inn github callback

web/app/login/page.tsx, web/app/page.tsx, web/app/register/page.tsx
This pull request adds authentication-aware logic to the main pages of the app, improving user experience by conditionally rendering content and navigation based on authentication status. The changes ensure that authenticated users are redirected appropriately and see relevant actions, while unauthenticated users are prompted to log in or register. Loading states are also handled more gracefully.
**Authentication-aware navigation and conditional rendering:**
* Added checks for authentication and loading state in `LoginPage` and `RegisterPage`, redirecting authenticated users to the home page and displaying a loading indicator when necessary (`web/app/login/page.tsx`, `web/app/register/page.tsx`). [[1]](diffhunk://#diff-a3f991f83bc1a6f1cd68b4942b7350d8bcb7670c09cbdaf05cb3e2e3e712d0efR1-R25) …
=> Fix details errors

backend/src/routes/auth/auth.ts, backend/src/routes/github/github.ts, backend/src/routes/google/google.ts, backend/src/routes/services/index.ts, backend/src/routes/services/subscription.ts, backend/src/routes/spotify/spotify.ts, documentation/area-documentation/docs/How to contribute/create-a-service.md, documentation/area-documentation/docs/How to contribute/service-subscription-flow.md, web/app/services/page.tsx
This pull request refactors and centralizes the service subscription logic for GitHub, Google, Spotify, and Timer services. It removes individual subscription endpoints from their respective service routes and consolidates them under a new shared subscription router. Additionally, it enhances logging for subscription status checks and unsubscriptions, and introduces a new endpoint for checking timer subscription status.
Key changes include:
**Subscription Endpoint Refactoring and Consolidation**
- Removed individual `/subscribe` endpoints and related Swagger documentation from `auth.ts`, `github.ts`, `google.ts`, and `spotify.ts`, and replaced them by mounting a new shared `subscriptionRouter` under `/auth` and updating all service endpoint references accordingly. This centralizes …
=> Centralize subscribe routes

web/app/dashboard/page.tsx, web/app/my-areas/page.tsx, web/app/page.tsx, web/app/services/page.tsx, web/app/verify/page.tsx, web/components/UserActions.tsx, web/components/header.tsx, web/components/login-form.tsx, web/components/password-form.tsx, web/components/reaction-form.tsx, web/components/register-form.tsx
This pull request makes a consistent UI improvement across the application by adding the `cursor-pointer` CSS class to all clickable buttons and interactive elements. This ensures that users always see the pointer cursor when hovering over interactive controls, improving usability and visual feedback.
Most important changes:
**Global UI Consistency:**
* Added `cursor-pointer` to all `Button` components and clickable elements in pages such as `dashboard`, `my-areas`, `services`, `verify`, and `home`, ensuring the pointer cursor appears on hover. [[1]](diffhunk://#diff-6788482cbad63f18a4deb2475a41846e6a351d413bec511654f8b6e9fa8b9154L177-R177) [[2]](diffhunk://#diff-6788482cbad63f18a4deb2475a41846e6a351d413bec511654f8b6e9fa8b9154L253-R253) …
=> Refacto button cursor pointer

web/app/page.tsx, web/components/UserActions.tsx, web/components/header.tsx, web/package.json
This pull request focuses on improving accessibility and semantic structure across the web app, particularly on the homepage and navigation components. Key changes include replacing non-semantic elements with appropriate heading tags, adding ARIA attributes for better screen reader support, and introducing a new accessibility check script.
**Accessibility and Semantic HTML Improvements:**
* Replaced `div` elements with semantic heading tags (`h1`, `h2`, `h3`, `h4`) throughout the homepage (`page.tsx`) and navigation (`header.tsx`) to improve document structure and assistive technology support. [[1]](diffhunk://#diff-4147e4214fb354e0420dcb3efbfec9df60fae2d3a2e1bdcfa43fb380ff475649L72-R87) [[2]](diffhunk://#diff-4147e4214fb354e0420dcb3efbfec9df60fae2d3a2e1bdcfa43fb380ff475649L114-R164) …
=> Wcag compilant on the main page
